spring:
  datasource:
    drive-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-36da6eb7-joshproject.e.aivencloud.com:25759/defaultdb?ssl-mode=REQUIRED
    username: avnadmin
    password: AVNS_4S9kMoKHVuzlaJofkZA
    hikari:
      connection-timeout: 5000        # espera máx 5s para obtener conexión del pool
      validation-timeout: 3000        # espera máx 3s para validar la conexión
  data:
    mongodb:
      uri: mongodb+srv://Admin:Admin@cluster0.wmnv2yp.mongodb.net/?appName=Cluster0
