spring:
  application:
    name: product-api

  profiles:
    active: dev

  graphql:
    graphiql:
        enabled: true

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  cache:
    type: redis

management:
  endpoints:
    web:
      exposure:
        include: env, health, info, circuitbreakers, circuitbreakerevents
  endpoint:
    health:
      show-details: always
    env:
      show-values: always
  health:
    circuitbreakers:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: https://tecylab-eureka-server-cabbbcdpb4hdargu.canadacentral-01.azurewebsites.net/eureka/
    fetch-registry: true
    register-with-eureka: true





